### PR TITLE
Add landing page

### PR DESCRIPTION
**Pull request by pbkabali**
### What this PR does

This PR adds the landing page

### Screenshot
image

### CODE REVIEW

**Review by tirthajyoti-ghosh — CHANGES_REQUESTED** [review]
# Changes required 🛑 

## What a remarkable project you have built 💯! This is impressive 🤩👌🧨! Awesome README and commit messages 💯 .

### But in order to get it approved, we need to work on some changes. Let's see...

- Your clone has a horizontal scrollbar 👇 

  image

  Please remove this.
  **IMPORTANT: avoid using `overflow-x: hidden`**

- Your footer changes its position when the screen height changed 👇 

| Source Page	| Clone Page |
|:---:|:---:|
|image|image|

  Please fix this.


Your project looks absolutely fantastic. Just make these changes and apply for another code review.

Happy coding 👨‍💻 

<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

**Comment by pbkabali** [comment]
Hello @tirthajyoti-ghosh, thank you for your review. We have worked on the feedback and submitted the review request again.

**Review by expjazz — APPROVED** [review]
## Status: Project Approved :green_circle: 

#### The page looks amazing, and you did a great job on the changes requested by my colleague :clap: 

Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

**Comment by pbkabali** [comment]
Thank you @expjazz for your time and prompt review

**Pull request merged**
